import type { Metadata } from "next";
import { Poppins , Inter } from "next/font/google";
import "./globals.css";

const PoppinsFont = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["600"]
});

const InterFont = Inter({
  variable :"--font-inter",
  subsets:["latin"],
  weight:["400" , "200" , "800" , "600"]

})



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${PoppinsFont.variable} ${InterFont.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
